# Generated by Django 5.0.7 on 2026-04-08 07:36

from django.db import migrations


def migrate_clinician_to_user(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(role__in=['clinician', 'viewer']).update(role='user')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_change_clinician_to_user_role'),
    ]

    operations = [
        migrations.RunPython(migrate_clinician_to_user, migrations.RunPython.noop),
    ]
