# Generated by Django 4.2.7 on 2026-06-06 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('hpv_status', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_screening_date', models.DateField(blank=True, null=True)),
                ('pregnancy_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('medical_history', models.TextField(blank=True, help_text='Previous medical conditions, surgeries, etc.', null=True)),
                ('medications', models.TextField(blank=True, help_text='Current medications', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('family_history', models.TextField(blank=True, help_text='Family history of relevant conditions', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='core.patient'),
        ),
    ]
