# Generated by Django 4.2.7 on 2026-06-09 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_patient_analysis_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Aadhaar number (12 digits)', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='abha_health_id',
            field=models.CharField(blank=True, help_text='ABHA Health ID number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='alternate_contact',
            field=models.CharField(blank=True, help_text='Alternate contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text="Patient's blood group", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_ai_analysis',
            field=models.BooleanField(default=False, help_text='Consent given for AI analysis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_image_capture',
            field=models.BooleanField(default=False, help_text='Consent given for image capture'),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_screening',
            field=models.BooleanField(default=False, help_text='Consent given for screening'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_figo_stage',
            field=models.CharField(blank=True, choices=[('0', 'Stage 0 - Pre-cancer'), ('IA1', 'Stage IA1'), ('IA2', 'Stage IA2'), ('IB1', 'Stage IB1'), ('IB2', 'Stage IB2'), ('IIA', 'Stage IIA'), ('IIB', 'Stage IIB'), ('IIIA', 'Stage IIIA'), ('IIIB', 'Stage IIIB'), ('IVA', 'Stage IVA'), ('IVB', 'Stage IVB')], help_text='Current FIGO staging if diagnosed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='digital_signature',
            field=models.TextField(blank=True, help_text='Digital signature (base64 encoded)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, help_text='District of residence', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='education_level',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], help_text="Patient's highest education level", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact person name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_number',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship with emergency contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated')], help_text="Patient's marital status", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, help_text='Medical Record Number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, help_text="Patient's occupation", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pin_code',
            field=models.CharField(blank=True, help_text='PIN/Postal code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, help_text='State of residence', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('treatment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment_type', models.CharField(choices=[('observation', 'Observation'), ('medication', 'Medication'), ('surgery', 'Surgery'), ('chemotherapy', 'Chemotherapy'), ('radiation', 'Radiation Therapy'), ('cryotherapy', 'Cryotherapy'), ('leep', 'LEEP Procedure'), ('conization', 'Cold Knife Conization'), ('hysterectomy', 'Hysterectomy'), ('trachelectomy', 'Trachelectomy'), ('immunotherapy', 'Immunotherapy'), ('palliative', 'Palliative Care'), ('other', 'Other')], help_text='Type of treatment', max_length=100)),
                ('start_date', models.DateField(help_text='Treatment start date')),
                ('end_date', models.DateField(blank=True, help_text='Treatment end date (if applicable)', null=True)),
                ('description', models.TextField(help_text='Treatment details and protocol')),
                ('outcome', models.TextField(blank=True, help_text='Treatment outcome/results', null=True)),
                ('side_effects', models.TextField(blank=True, help_text='Side effects experienced', null=True)),
                ('hospital_facility', models.CharField(blank=True, help_text='Facility where treatment was given', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='core.patient')),
                ('prescribing_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treatment Record',
                'verbose_name_plural': 'Treatment Records',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screening_date', models.DateField(help_text='Date of screening')),
                ('screening_type', models.CharField(choices=[('pap_smear', 'Pap Smear'), ('hpv_test', 'HPV Test'), ('hpv_vaccination', 'HPV Vaccination'), ('colposcopy', 'Colposcopy'), ('biopsy', 'Biopsy'), ('visual_inspection', 'Visual Inspection with Acetic Acid'), ('mri', 'MRI Scan'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('other', 'Other')], help_text='Type of screening procedure', max_length=50)),
                ('facility_name', models.CharField(help_text='Name of facility where screening was done', max_length=200)),
                ('result', models.TextField(help_text='Screening result details')),
                ('findings', models.TextField(blank=True, help_text='Additional findings from screening', null=True)),
                ('uploaded_report', models.ImageField(blank=True, help_text='Uploaded screening report image', null=True, upload_to='screening_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_records', to='core.patient')),
            ],
            options={
                'verbose_name': 'Screening Record',
                'verbose_name_plural': 'Screening Records',
                'ordering': ['-screening_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], help_text='Overall risk level assessment', max_length=20)),
                ('risk_factors', models.JSONField(default=dict, help_text='Identified risk factors with scores')),
                ('recommendations', models.TextField(help_text='Clinical recommendations based on risk assessment')),
                ('next_review_date', models.DateField(blank=True, help_text='Date for next risk assessment review', null=True)),
                ('age_risk', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True)),
                ('hpv_risk', models.CharField(blank=True, choices=[('negative', 'Negative'), ('positive_low_risk', 'Positive (Low Risk HPV)'), ('positive_high_risk', 'Positive (High Risk HPV)'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('symptoms_risk', models.CharField(blank=True, choices=[('asymptomatic', 'Asymptomatic'), ('symptomatic_benign', 'Symptomatic (likely benign)'), ('symptomatic_concerning', 'Symptomatic (concerning)')], max_length=30, null=True)),
                ('family_history_risk', models.BooleanField(default=False, help_text='Family history of cervical cancer')),
                ('immunocompromised', models.BooleanField(default=False, help_text='Patient is immunocompromised')),
                ('smoking_status', models.CharField(blank=True, choices=[('non_smoker', 'Non-smoker'), ('former_smoker', 'Former Smoker'), ('current_smoker', 'Current Smoker')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='core.patient')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReproductiveHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregnancies_count', models.IntegerField(blank=True, default=0, help_text='Total number of pregnancies', null=True)),
                ('deliveries_count', models.IntegerField(blank=True, default=0, help_text='Total number of deliveries', null=True)),
                ('abortions_count', models.IntegerField(blank=True, default=0, help_text='Total number of abortions/miscarriages', null=True)),
                ('live_births', models.IntegerField(blank=True, default=0, help_text='Number of live births', null=True)),
                ('complications', models.TextField(blank=True, help_text='Pregnancy/delivery complications', null=True)),
                ('infertility_history', models.TextField(blank=True, help_text='History of infertility treatments', null=True)),
                ('fertility_treatments', models.TextField(blank=True, help_text='Fertility treatments undergone', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repro_history', to='core.patient')),
            ],
            options={
                'verbose_name': 'Reproductive History',
                'verbose_name_plural': 'Reproductive Histories',
            },
        ),
        migrations.CreateModel(
            name='GynecologicalHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menarche_age', models.IntegerField(blank=True, help_text='Age at first menstruation', null=True)),
                ('menopause_age', models.IntegerField(blank=True, help_text='Age at menopause', null=True)),
                ('menstrual_history', models.TextField(blank=True, help_text='Menstrual pattern details (regularity, flow, etc.)', null=True)),
                ('last_pap_smear', models.DateField(blank=True, help_text='Date of last Pap smear test', null=True)),
                ('last_pap_result', models.CharField(blank=True, help_text='Result of last Pap smear', max_length=50, null=True)),
                ('contraceptive_use', models.TextField(blank=True, help_text='Current/past contraceptive methods', null=True)),
                ('sexual_history', models.TextField(blank=True, help_text='Relevant sexual history (if disclosed)', null=True)),
                ('last_colposcopy', models.DateField(blank=True, help_text='Date of last colposcopy', null=True)),
                ('colposcopy_findings', models.TextField(blank=True, help_text='Colposcopy findings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gyn_history', to='core.patient')),
            ],
            options={
                'verbose_name': 'Gynecological History',
                'verbose_name_plural': 'Gynecological Histories',
            },
        ),
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('followup_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='Date follow-up is scheduled')),
                ('completed_date', models.DateField(blank=True, help_text='Date follow-up was completed', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='pending', help_text='Current status of follow-up', max_length=20)),
                ('purpose', models.CharField(help_text="Purpose of follow-up (e.g., 'Review Pap results', 'Post-treatment check')", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about follow-up', null=True)),
                ('findings', models.TextField(blank=True, help_text='Findings from follow-up visit', null=True)),
                ('next_action', models.TextField(blank=True, help_text='Recommended next action after follow-up', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='core.patient')),
            ],
            options={
                'verbose_name': 'Follow-up Record',
                'verbose_name_plural': 'Follow-up Records',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField(help_text='Date and time of appointment')),
                ('appointment_type', models.CharField(choices=[('screening', 'Screening Appointment'), ('follow_up', 'Follow-up Appointment'), ('consultation', 'Consultation'), ('treatment', 'Treatment Session'), ('colposcopy', 'Colposcopy'), ('biopsy', 'Biopsy'), ('post_op', 'Post-Operative Check'), ('emergency', 'Emergency Visit'), ('telehealth', 'Telehealth Consultation')], help_text='Type of appointment', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', help_text='Appointment status', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', help_text='Appointment priority', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for appointment', null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether appointment reminder was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
