# Generated by Django 4.2.7 on 2026-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='batch_aggregated_data',
            field=models.JSONField(blank=True, help_text='Aggregated results for batch primary analysis', null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID of the batch this analysis belongs to', null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='batch_position',
            field=models.IntegerField(blank=True, help_text='Position of this image in the batch (1-indexed)', null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='batch_total_count',
            field=models.IntegerField(blank=True, help_text='Total number of images in the batch', null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='is_batch_primary',
            field=models.BooleanField(default=False, help_text='Whether this is the primary analysis showing aggregated results'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='age_at_first_pregnancy',
            field=models.IntegerField(blank=True, help_text='Age at first pregnancy', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='age_at_first_sexual_intercourse',
            field=models.IntegerField(blank=True, help_text='Age at first sexual intercourse', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence score from latest analysis', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='alcohol_use',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('occasional', 'Occasional'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='diabetes',
            field=models.BooleanField(default=False, help_text='Patient has diabetes'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='diabetes_type',
            field=models.CharField(blank=True, choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('gestational', 'Gestational')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='family_history_details',
            field=models.TextField(blank=True, help_text='Details of family history', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('negative', 'Negative'), ('positive', 'Positive'), ('unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='hpv_vaccinated',
            field=models.BooleanField(default=False, help_text='HPV vaccinated'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='hpv_vaccine_doses',
            field=models.IntegerField(blank=True, help_text='Number of HPV vaccine doses received', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='immunocompromised_details',
            field=models.TextField(blank=True, help_text='Details of immunocompromised status', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='last_pap_smear_date',
            field=models.DateField(blank=True, help_text='Date of last Pap smear', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='last_pap_smear_result',
            field=models.CharField(blank=True, help_text='Result of last Pap smear', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='number_of_pregnancies',
            field=models.IntegerField(blank=True, help_text='Number of pregnancies', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='oral_contraceptive_use',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('past', 'Past User'), ('current', 'Current User')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='oral_contraceptive_years',
            field=models.IntegerField(blank=True, help_text='Years of oral contraceptive use', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='previous_abnormal_pap',
            field=models.BooleanField(default=False, help_text='Previous abnormal Pap smear results'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='previous_abnormal_pap_details',
            field=models.TextField(blank=True, help_text='Details of previous abnormal results', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Overall risk score from 0-100'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='screening_recommendation',
            field=models.CharField(choices=[('routine', 'Routine Screening'), ('annual', 'Annual Screening'), ('semi_annual', 'Semi-annual (6 months)'), ('quarterly', 'Quarterly (3 months)'), ('immediate', 'Immediate Follow-up')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='sexual_partners_count',
            field=models.IntegerField(blank=True, help_text='Number of lifetime sexual partners', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='smoking_years',
            field=models.IntegerField(blank=True, help_text='Years of smoking', null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='immunocompromised',
            field=models.BooleanField(default=False, help_text='Patient is immunocompromised (other than HIV)'),
        ),
    ]
