# Generated by Django 5.2.15 on 2026-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_analysis_recommended_checkups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('senior_technician', 'Senior Technician'), ('user', 'Doctor/User'), ('patient', 'Patient')], default='user', max_length=20),
        ),
    ]
