# Generated by Django 5.2.15 on 2026-06-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='abha_health_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alternate_contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consent_ai_analysis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consent_image_capture',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consent_screening',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='current_figo_stage',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='digital_signature',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='district',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_record_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
    ]
