# Generated by Django 4.2.7 on 2026-06-23 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_clinicalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'senior_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients_technician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PapSmearTest',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('+ve', 'Positive (+ve)'), ('-ve', 'Negative (-ve)')], help_text='Pap smear test result', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional technician notes', null=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_smear_tests', to='core.patient')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_pap_smears', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckupRecommendation',
            fields=[
                ('checkup_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hpv_pcr_testing', models.BooleanField(default=False, help_text='Recommend HPV PCR Testing')),
                ('colposcopy', models.BooleanField(default=False, help_text='Recommend Colposcopy')),
                ('histopathology', models.BooleanField(default=False, help_text='Recommend Histopathology (Gold Standard)')),
                ('mri_scan', models.BooleanField(default=False, help_text='Recommend MRI (only for confirmed invasive cancer)')),
                ('treatment_follow_up', models.TextField(blank=True, help_text='Treatment & Follow-up plan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_checkups', to=settings.AUTH_USER_MODEL)),
                ('pap_smear_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_checkups', to='core.papsmeartest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_recommendations', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
