# Generated by Django 5.2.15 on 2026-06-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patient_assigned_doctor_patient_assigned_technician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuprecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followuprecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='gynecologicalhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='reproductivehistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='screeningrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatmentrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatmentrecord',
            name='prescribing_doctor',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='FollowUpRecord',
        ),
        migrations.DeleteModel(
            name='GynecologicalHistory',
        ),
        migrations.DeleteModel(
            name='ReproductiveHistory',
        ),
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
        migrations.DeleteModel(
            name='ScreeningRecord',
        ),
        migrations.DeleteModel(
            name='TreatmentRecord',
        ),
    ]
